### PR TITLE
Fix links to github sources

### LINKED ISSUE #228: Broken links to Nix expressions on GitHub
search.nixos.org provides broken links to the Nix expression source code on GitHub for packages, such as the following: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/14cf906f33c.tar.gz/pkgs/applications/editors/emacs-modes/libgenerated.nix#L72. Seems like just the SHA-1 (without `.tar.gz`) or the channel should be included in the URL.

### PR DESCRIPTION
**Pull request by turboMaCk**
Closes #228

### CODE REVIEW

File: src/Page/Packages.elm [hunk 1]
```diff
@@ -248,18 +249,18 @@ viewResultItemDetails channel item =
...
+                |> Maybe.withDefault Regex.never
+                >> (\reg -> Regex.replace reg (\_ -> ""))
 
         asGithubLink value =
             case Search.channelDetailsFromId channel of
                 Just channelDetails ->
                     a
-                        [ href <| githubUrlPrefix channelDetails.branch ++ (value |> String.replace ":" "#L" |> cleanPosition) ]
+                        [ href <| githubUrlPrefix channelDetails.branch ++ (value |> String.replace ":" "#L" |> cleanPosition)
+                        , target "blank_"
```
Comment (turboMaCk) [inline src/Page/Packages.elm:262]:
```suggestion
                        , target "_blank"
```

**Review by garbas — APPROVED** [review]

**Comment by garbas** [comment]
:1st_place_medal:
